Chore/add impact roles okta sync
futurice/haskell-mega-repo pull request #902
Opened 2022-06-29 14:20 UTC by thaiscristine

2022-06-29 14:23 UTC, thaiscristine commented
This PR is to solve [this ticket](https://support.futurice.com/helpdesk/tickets/26175). @lumicake Do you know if any extra step is required? Such as updating hmrs, for example

2022-07-04 08:50 UTC, jvanbruegge approved these changes

2022-07-05 07:43 UTC, lumicake requested changes
Looks good, I think there's one change needed for this to actually work.

2022-07-05 07:43 UTC, lumicake commented on personio-client/src/Personio/Types/Employee.hs
> +    , _employeeImpactRoles       :: !(Maybe Text)
This data is coming from Personio? You need to add an accompanying line in the actual parsing of the data from Personio, I believe.

For example, look at line 95:
```haskell
, _employeePowerBiSecurityGroup       :: !(Maybe Text)
```

it has an accompanying line (line#214) in the `parseEmployeeObject` function:
```haskell
<*> optional (parseDynamicAttribute obj "Access rights to PowerBI security group")
```

You need to add this kind of parsing for impact roles as well.

2022-07-05 07:45 UTC, lumicake commented
> 

I believe these changes should be sufficient :)

2023-04-04 12:20 UTC, closed without merging